# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('embarazos', '0021_auto_20160915_1100'),
        ('pacientes', '0026_auto_20160713_1108'),
        ('establecimientos', '0009_auto_20160705_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('tipo', models.CharField(default='parto', max_length=20, verbose_name='Tipo de ingreso', choices=[('parto', 'Parto'), ('aborto', 'Aborto')])),
                ('inicio', models.CharField(default='espontaneo', max_length=20, verbose_name='Inicio', choices=[('espontaneo', 'Espont\xe1neo'), ('inducido', 'Inducido')])),
                ('cama', models.SmallIntegerField(null=True, verbose_name='Cama', blank=True)),
                ('visito_sintomas', models.BooleanField(default=False)),
                ('asintomatica', models.BooleanField(default=False, verbose_name='Asintom\xe1tica')),
                ('eg_fum', models.CharField(default=None, max_length=20, null=True, verbose_name='EG FUM', blank=True)),
                ('eg_ecografia', models.CharField(default=None, max_length=20, null=True, verbose_name='EG ecograf\xeda', blank=True)),
                ('eg_altura_uterina', models.CharField(default=None, max_length=20, null=True, verbose_name='EG altura uterina', blank=True)),
                ('eg_elegida', models.CharField(default='fum', max_length=20, verbose_name='EG escogida', blank=True, choices=[('fum', 'FUM'), ('ecografia', 'Ecograf\xeda'), ('altura uterina', 'Altura Uterina')])),
                ('edad_gestacional_semanas', models.CharField(max_length=5, null=True, blank=True)),
                ('fecha_probable_parto_fum', models.DateField(null=True, verbose_name='FPP FUM', blank=True)),
                ('fecha_probable_parto_ecografia', models.DateField(null=True, verbose_name='FPP ecografia', blank=True)),
                ('fecha_probable_parto_altura_uterina', models.DateField(null=True, verbose_name='FPP altura uterina', blank=True)),
                ('peso', models.FloatField(default=0, verbose_name='Peso actual', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('imc', models.FloatField(verbose_name='IMC')),
                ('imc_clasificacion', models.CharField(max_length=20, null=True, verbose_name='IMC clasificacion', blank=True)),
                ('temperatura', models.FloatField(blank=True, null=True, verbose_name='Temperatura', validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)])),
                ('presion_sistolica', models.SmallIntegerField(blank=True, null=True, verbose_name='Presion sistolica', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('presion_diastolica', models.SmallIntegerField(blank=True, null=True, verbose_name='Presion diastolica', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pulso', models.PositiveSmallIntegerField(blank=True, max_length=2, null=True, verbose_name='Pulso', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('frecuencia_respiratoria', models.SmallIntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('altura_uterina', models.SmallIntegerField(blank=True, null=True, verbose_name='Altura uterina', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(40)])),
                ('situacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Situacion', choices=[('longitudinal', 'Longitudinal'), ('transversal', 'Transversal'), ('na', 'NA')])),
                ('presentacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Presentacion', choices=[('cefalico', 'Cefalico'), ('podalico', 'Podalico'), ('na', 'NA')])),
                ('posicion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Posicion', choices=[('derecho', 'Derecho'), ('izquierdo', 'Izquierdo'), ('na', 'NA')])),
                ('fcf', models.SmallIntegerField(blank=True, max_length=3, null=True, verbose_name='FCF', validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(400)])),
                ('movimientos_fetales', models.CharField(blank=True, max_length=5, null=True, verbose_name='Movimientos fetales', choices=[('sm', 'Sin Movimiento'), ('+', '+'), ('++', '++'), ('+++', '+++'), ('na', 'NA')])),
                ('dinamica_uterina', models.CharField(blank=True, max_length=5, null=True, verbose_name='Dinamica uterina', choices=[('sd', 'Sin Dinamica'), ('+', '+'), ('++', '++'), ('+++', '+++'), ('na', 'NA')])),
                ('edemas', models.CharField(blank=True, max_length=5, null=True, verbose_name='Edemas', choices=[('se', 'Sin Edemas'), ('+', '+'), ('++', '++'), ('+++', '+++')])),
                ('reflejos', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reflejos', choices=[('0', '0'), ('+', '+'), ('++', '++'), ('+++', '+++')])),
                ('lugar_de_derivacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Lugar de derivaci\xf3n', choices=[('sala de dilatacion', 'Sala de dilataci\xf3n'), ('sala de expulsion', 'Sala de expulsi\xf3n'), ('domicilio', 'Domicilio'), ('otros', 'Otros')])),
                ('lugar_de_derivacion_otros', models.CharField(max_length=50, null=True, verbose_name='Otros', blank=True)),
                ('atencion_fonp', models.BooleanField(default=False, verbose_name='FONP')),
                ('atencion_fonb', models.BooleanField(default=False, verbose_name='FONB')),
                ('atencion_foni', models.BooleanField(default=False, verbose_name='FONI')),
                ('atencion_fone_1', models.BooleanField(default=False, verbose_name='FONE I')),
                ('atencion_fone_2', models.BooleanField(default=False, verbose_name='FONE II')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
                ('embarazo', models.OneToOneField(related_name='ingreso', to='embarazos.Embarazo')),
                ('establecimiento', models.ForeignKey(related_name='ingresos', to='establecimientos.Establecimiento')),
                ('paciente', models.ForeignKey(related_name='ingresos', to='pacientes.Paciente')),
            ],
            options={
                'ordering': ('fecha', 'hora'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Partograma',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(default='abierto', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(related_name='partogramas', to='establecimientos.Establecimiento')),
                ('ingreso', models.OneToOneField(related_name='partograma', to='partos.Ingreso')),
                ('paciente', models.ForeignKey(related_name='partogramas', to='pacientes.Paciente')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PartogramaMedicion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('soluciones', models.NullBooleanField(default=None, verbose_name='Soluciones')),
                ('solucion', models.CharField(max_length=100, verbose_name='Soluci\xf3n', blank=True)),
                ('tocolisis', models.CharField(max_length=100, verbose_name='Tocolisis', blank=True)),
                ('oxitocina', models.CharField(max_length=100, verbose_name='Oxitocina', blank=True)),
                ('goteo', models.CharField(max_length=100, verbose_name='Goteo', blank=True)),
                ('presion_sistolica', models.SmallIntegerField(blank=True, null=True, verbose_name='Presion sistolica', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('presion_diastolica', models.SmallIntegerField(blank=True, null=True, verbose_name='Presion diastolica', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pulso', models.PositiveSmallIntegerField(blank=True, max_length=2, null=True, verbose_name='Pulso', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('frecuencia_respiratoria', models.SmallIntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('temperatura', models.FloatField(blank=True, null=True, verbose_name='Temperatura', validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)])),
                ('moldeaminetos', models.CharField(blank=True, max_length=10, null=True, verbose_name='Moldeaminetos', choices=[('1', '1'), ('2', '2')])),
                ('du_frecuencia', models.CharField(blank=True, max_length=10, verbose_name='Frecuencia', choices=[('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5+/10', '5+/10')])),
                ('du_duracion', models.CharField(blank=True, max_length=20, verbose_name='Duraci\xf3n', choices=[('-20', 'menos de 20'), ('20 - 24', '20 a 24'), ('25 - 29', '25 a 29'), ('30 - 34', '30 a 34'), ('35 - 39', '35 a 39'), ('40+', '40 a mas')])),
                ('du_intensidad', models.CharField(blank=True, max_length=10, verbose_name='Intensidad', choices=[('+', '+'), ('++', '++'), ('+++', '+++')])),
                ('fcf', models.SmallIntegerField(blank=True, max_length=3, null=True, verbose_name='FCF', validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(400)])),
                ('tv_dilatacion', models.SmallIntegerField(blank=True, null=True, verbose_name='Dilataci\xf3n', choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10')])),
                ('tv_incorporacion', models.CharField(blank=True, max_length=20, verbose_name='Incorporaci\xf3n', choices=[('-40%', 'menos de 40%'), ('50%', '50%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%')])),
                ('tv_descenso_cefalico', models.CharField(blank=True, max_length=5, null=True, verbose_name='Descenso cef\xe1lico', choices=[('0', '0 || -4'), ('1', '1 || -3'), ('2', '2 || -2'), ('3', '3 || -1/0'), ('4', '4 || +1/+2'), ('5', '5 || +3/+4')])),
                ('tv_membranas', models.CharField(blank=True, max_length=10, verbose_name='Membranas', choices=[('integras', '\xcdntegras'), ('rotas', 'Rotas')])),
                ('tv_membranas_rotas_tipo', models.CharField(blank=True, max_length=10, verbose_name='', choices=[('artificial', 'Artificial'), ('espontanea', 'Espontanea')])),
                ('tv_liquido_amniotico', models.CharField(blank=True, max_length=20, null=True, verbose_name='L\xedquido amni\xf3tico', choices=[('claro', 'Claro'), ('meconial', 'Meconial'), ('sanguinolento', 'Sanguinolento')])),
                ('tv_variedad_presentacion_val1', models.CharField(blank=True, max_length=20, null=True, choices=[('anterior', 'Anterior'), ('transverso', 'Transverso'), ('posterior', 'Posterior')])),
                ('tv_variedad_presentacion_val2', models.CharField(blank=True, max_length=20, null=True, choices=[('derecho', 'Derecho'), ('izquierdo', 'Izquierdo'), ('no aplica', 'No aplica')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
                ('partograma', models.ForeignKey(related_name='mediciones', to='partos.Partograma')),
            ],
            options={
                'ordering': ('fecha', 'hora'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TerminacionEmbarazo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipo', models.CharField(default='unico', max_length=20, choices=[('unico', '\xdanico'), ('multiple', 'M\xfaltiple')])),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('terminacion', models.CharField(default='parto espontaneo', choices=[('parto espontaneo', 'Parto espontaneo'), ('forceps', 'Forces'), ('vacuum', 'Vacuum'), ('cesarea electiva', 'Ces\xe1rea electiva'), ('cesarea emergencia', 'Ces\xe1rea emergencia')], max_length=20, blank=True, null=True, verbose_name='Terminaci\xf3n')),
                ('procedimiento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo procedimiento', choices=[('corporal', 'Corporal'), ('segmentaria', 'Segmentaria'), ('no aplica', 'No aplica')])),
                ('posicion_gestante', models.CharField(default='horizontal', choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('no aplica', 'No aplica')], max_length=20, blank=True, null=True, verbose_name='Posici\xf3n gestante')),
                ('acompaniante', models.BooleanField(default=False, verbose_name='Parto con acompa\xf1ante')),
                ('duracion', models.CharField(default='normal', choices=[('normal', 'Normal'), ('prolongado', 'Prolongado'), ('precipitado', 'Precipitado'), ('no aplica', 'No aplica')], max_length=20, blank=True, null=True, verbose_name='Duraci\xf3n')),
                ('muerte_intrauterina', models.CharField(default='no hubo', choices=[('no hubo', 'No hubo'), ('durante embarazo', 'Durante embarazo'), ('durante parto', 'Durante parto'), ('momento desconocido', 'Momento desconocido')], max_length=20, blank=True, null=True, verbose_name='Muerte intrauterina')),
                ('episiotomia', models.NullBooleanField(default=None, verbose_name='Episiotom\xeda')),
                ('desgarros', models.CharField(default='no hubo', choices=[('no hubo', 'No hubo'), ('grado I', 'Grado I'), ('grado II', 'Grado II'), ('grado III/IV', 'Grado III/IV'), ('no aplica', 'No aplica')], max_length=20, blank=True, null=True, verbose_name='Desgarros')),
                ('alumbramiento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alumbramiento', choices=[('activo', 'Activo'), ('expontaneo', 'Expontaneo'), ('manual', 'Manual')])),
                ('placenta', models.CharField(default='completa', choices=[('completa', 'Completa'), ('imcompleta', 'Incompleta'), ('retenida', 'Retenida')], max_length=20, blank=True, null=True, verbose_name='Placenta')),
                ('ligadura_cordon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ligadura cord\xf3n', choices=[('precoz', 'Precoz'), ('temprana', 'Temprana'), ('tardia', 'Tard\xeda')])),
                ('cordon_umbilical', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cordon Umbilical', choices=[('normal', 'Normal'), ('vasos incompletos', 'Vasos Incompletos'), ('corto', 'Corto'), ('circular simple', 'Circular Simple'), ('circular doble', 'Circular Doble')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(related_name='terminacion_embarazos_c', to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(related_name='terminaciones_embarazo', to='establecimientos.Establecimiento')),
                ('ingreso', models.OneToOneField(related_name='terminacion_embarazo', to='partos.Ingreso')),
                ('modifier', models.ForeignKey(related_name='terminacion_embarazos_m', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(related_name='terminaciones_embarazo', to='pacientes.Paciente')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
