from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(r'^partograma/(?P<partograma_id>\d+)/pdf/$',
        views.PartogramaReportView.as_view(), name='partograma_pdf'),
    url(r'^partograma/(?P<partograma_id>\d+)/grafica-controles-vitales/pdf/$',
        views.GraficaControlesVitalesView.as_view(
        ), name='grafica_controles_vitales'),
    url(r'^hoja-de-monitoreo-materno-fetal/(?P<partograma_id>\d+)/$',
        views.HojaMonitoreoMaternoFetalReportView.as_view(), name='hoja_monitoreo_materno_fetal'),
    url(r'^partos-historia-clinica/(?P<embarazo_id>\d+)/$',
        views.PartosHistoriaClinicaReportView.as_view(), name='partos_historia_clinica'),
    url(r'^partos-controles-prenatal/(?P<embarazo_id>\d+)/$',
        views.PartosControlesPrenatalReportView.as_view(), name='partos_controles_prenatal'),
    url(r'^partograma/resumen-pdf/$', views.ResumenPartoReportView.as_view(), name='parto_pdf'),
    url(r'^partograma/partograma-pdf/$', views.PartogramaHomeReportView.as_view(), name='partograma_home_pdf'),
)

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^reportes/', include(reports, namespace='reports')),
    url(r'^registrar-ingreso/(?P<paciente_id>\d+)/$', views.IngresoCreateView.as_view(), name='ingreso_register'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/editar/$', views.IngresoUpdateView.as_view(), name='ingreso_edit'),
    url(r'^paciente/(?P<id>\d+)/$', views.PPacienteDetailView.as_view(), name='paciente_detail'),
    url(r'^paciente/(?P<id>\d+)/editar/$', views.PPacienteUpdateView.as_view(), name='paciente_update'),
    url(r'^paciente-control/(?P<id>\d+)/editar/$', views.PPacienteControlUpdateView.as_view(),
        name='paciente_control_update'),
    url(r'^paciente/registro/$', views.PPacienteCreateView.as_view(), name='paciente_create'),
    url(r'^paciente/crear/(?P<id>\d+)$', views.PPacienteCreateForceView.as_view(), name='paciente_create_force'),
    url(r'^paciente/(?P<id>\d+)/antecedentes/$', views.PPacienteAntecedentesDetailView.as_view(),
        name='paciente_antecedentes'),
    url(r'^paciente/(?P<id>\d+)/antecedentes/editar/$', views.PPacienteAntecedentesUpdateView.as_view(),
        name='paciente_antecedentes_edit'),
    url(r'^paciente/(?P<id>\d+)/antecedentes-familiares/$', views.PAntecedentesFamiliaresView.as_view(),
        name='paciente_antecedentes_familiares_edit'),
    url(r'^(?P<id>\d+)/antecedentes-medicos/$', views.PAntecedentesMedicosView.as_view(),
        name='paciente_antecedentes_medicos_edit'),
    url(r'^paciente/buscar/$', views.PPacienteSearchView.as_view(), name='paciente_search'),
    url(r'^(?P<paciente_id>\d+)/embarazos-previos/$', views.PUltimosEmbarazosView.as_view(),
        name='embarazos_ultimos_embarazos'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo/$', views.PUltimoEmbarazoCreateView.as_view(),
        name='embarazos_ultimo_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/$', views.PUltimoEmbarazoUpdateView.as_view(),
        name='embarazos_ultimo_embarazo_edit'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/eliminar/$', views.PUltimoEmbarazoDeleteView.as_view(),
        name='embarazos_ultimo_embarazo_delete'),
    url(r'^embarazo/(?P<paciente_id>\d+)/registrar-embarazo/$', views.PEmbarazoCreateView.as_view(),
        name='embarazo_create'),
    url(r'^embarazo/(?P<paciente_id>\d+)/editar-embarazo-actual/$', views.PEmbarazoUpdateCurrentView.as_view(),
        name='update_current'),
    url(r'^embarazo/(?P<paciente_id>\d+)/ecografias/$', views.PEcografiasView.as_view(), name='ecografias'),
    url(r'^embarazo/(?P<paciente_id>\d+)/agregar-ecografia/$', views.PEcografiaCreateView.as_view(),
        name='ecografia_create'),
    url(r'^embarazo/(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/editar/$', views.PEcografiaUpdateView.as_view(),
        name='ecografia_edit'),
    url(r'^embarazo/(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/eliminar/$', views.PEcografiaDeleteView.as_view(),
        name='ecografia_delete'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/sintomas/edit/$', views.PSintomasView.as_view(), name='sintomas'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/laboratorio/editar/$', views.PLaboratorioView.as_view(), name='laboratorio'),
    url(r'^(?P<ingreso_id>\d+)/registrar-termino-embarazo/$', views.TerminacionEmbarazoCreateView.as_view(),
        name='registrar_termino_embarazo'),
    url(r'^terminacion-embarazo/(?P<terminacion_embarazo_id>\d+)/editar/$',
        views.TerminacionEmbarazoUpdateView.as_view(
        ), name='terminacion_embarazo_edit'),
    url(r'^(?P<ingreso_id>\d+)/partograma/$',
        views.PartogramaView.as_view(), name='partograma'),
    url(r'^(?P<ingreso_id>\d+)/partograma/medicion/(?P<medicion_id>\d+)/$',
        views.PartogramaMedicionUpdateView.as_view(
        ), name='partograma_medicion'),
    url(r'^(?P<ingreso_id>\d+)/partograma/chart-data/',
        views.PartogramaChartDataView.as_view(),
        name='partograma_chart_data'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/examen-fisico/editar/$',
        views.PExamenFisicoView.as_view(),
        name='examen_fisico'),
    url(r'^control/(?P<id>\d+)/ultimo-control/$',
        views.UltimoControlView.as_view(), name='ultimo_control'),
    url(r'^referidas/$', views.ReferidasView.as_view(), name='pacientes_referidas'),
)
