from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/(?P<accion_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^tamizaje-depresion/(?P<embarazo_id>\d+)/$',
        views.TamizajeDepresionReportView.as_view(),
        name='tamizaje_depresion'),
)

urlpatterns = patterns(
    '',
    url(r'^reportes/',
        include(reports, namespace='reports')),
    url(r'^(?P<paciente_id>\d+)/embarazos-previos/$',
        views.UltimosEmbarazosView.as_view(),
        name='ultimos_embarazos'),
    url(r'^(?P<paciente_id>\d+)/ecografias/$',
        views.EcografiasView.as_view(),
        name='ecografias'),
    url(r'^(?P<paciente_id>\d+)/agregar-ecografia/$',
        views.EcografiaCreateView.as_view(),
        name='ecografia_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/editar/$',
        views.EcografiaUpdateView.as_view(),
        name='ecografia_edit'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo/$',
        views.UltimoEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/$',
        views.UltimoEmbarazoUpdateView.as_view(),
        name='ultimo_embarazo_edit'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/eliminar/$',
        views.UltimoEmbarazoDeleteView.as_view(),
        name='ultimo_embarazo_delete'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo/$',
        views.EmbarazoCreateView.as_view(),
        name='create'),
    url(r'^(?P<paciente_id>\d+)/registrar-control-embarazo/$',
        views.EmbarazoControlCreateView.as_view(),
        name='create-control-embarazo'),
    url(r'^(?P<paciente_id>\d+)/editar-embarazo-actual/$',
        views.EmbarazoUpdateCurrentView.as_view(),
        name='update_current'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/$',
        views.PlanPartoView.as_view(),
        name='plan_parto'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/edit/$',
        views.PlanPartoUpdateView.as_view(),
        name='plan_parto_edit'),
    url(r'^(?P<paciente_id>\d+)/terminar-embarazo/(?P<embarazo_id>\d+)/$',
        views.TerminarEmbarazoView.as_view(),
        name='terminar_embarazo'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo'
        r'/embarazo/(?P<embarazo_id>\d+)/$',
        views.UltimoEmbarazoFromEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_from_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/eliminar/$',
        views.EcografiaDeleteView.as_view(),
        name='ecografia_delete'),
    url(r'^(?P<paciente_id>\d+)/editar-violencia-genero/$',
        views.ViolenciaGeneroUpdateCurrentView.as_view(),
        name='violencia_update'),
)
